modLoader="javafml"
loaderVersion="[37,)"
#updateJSONURL="http://myurl.me/"
issueTrackerURL="https://github.com/gigaherz/HudCompass/issues"
displayURL="https://github.com/gigaherz/HudCompass"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java"
authors="gigaherz"
license="BSD (3 Clause)"

[[mods]]
modId="jsonthings"
version="${file.jarVersion}"
displayName="Json Things"
description='''
Things, in JSON sauce.
'''

[[dependencies.jsonthings]]
   modId="forge"
   mandatory=true
   versionRange="[37.0.31,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.jsonthings]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.17.1,1.18)"
   ordering="NONE"
   side="BOTH"