modLoader="javafml"
loaderVersion="[36,)"
license="BSD (3 Clause)"

[[mods]]
modId="jsonthings"
version="${file.jarVersion}"
displayName="Json Things"
logoFile="jsonthings-logo.png"
description='''
Things, in JSON sauce.
'''
authors="gigaherz"
#credit="Thanks for this example mod goes to Java"
issueTrackerURL="https://github.com/gigaherz/JsonThings/issues"
displayURL="https://github.com/gigaherz/JsonThings"

[[dependencies.jsonthings]]
   modId="forge"
   mandatory=true
   versionRange="[36.2.0,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.jsonthings]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"